import { v4 as uuidv4 } from 'uuid';
import { Case, InsuranceInfo } from '../../store/slices/types/caseManagementTypes';

export const mockInsurances: InsuranceInfo[] = [
  {
    id: uuidv4(),
    provider: 'Blue Cross Blue Shield',
    policyNumber: 'BCBS-12345678',
    coverageType: 'Comprehensive',
    startDate: '2023-01-01',
    endDate: '2023-12-31',
    contactPerson: 'Jane Smith',
    contactPhone: '(555) 123-4567',
    coverageDetails: 'Full coverage with $500 deductible',
    isActive: true,
  },
  {
    id: uuidv4(),
    provider: 'Aetna',
    policyNumber: 'AET-87654321',
    coverageType: 'Basic',
    startDate: '2023-03-15',
    endDate: '2024-03-14',
    contactPerson: 'John Davis',
    contactPhone: '(555) 987-6543',
    coverageDetails: 'Basic coverage with $1000 deductible',
    isActive: true,
  },
  {
    id: uuidv4(),
    provider: 'United Healthcare',
    policyNumber: 'UHC-24681357',
    coverageType: 'Premium',
    startDate: '2023-06-01',
    endDate: '2024-05-31',
    contactPerson: 'Michael Johnson',
    contactPhone: '(555) 456-7890',
    coverageDetails: 'Premium coverage with $250 deductible',
    isActive: true,
  },
  {
    id: uuidv4(),
    provider: 'Cigna',
    policyNumber: 'CIG-13579246',
    coverageType: 'Standard',
    startDate: '2023-02-15',
    endDate: '2024-02-14',
    contactPerson: 'Sarah Wilson',
    contactPhone: '(555) 789-0123',
    coverageDetails: 'Standard coverage with $750 deductible',
    isActive: false,
  },
  {
    id: uuidv4(),
    provider: 'Humana',
    policyNumber: 'HUM-97531246',
    coverageType: 'Senior Care',
    startDate: '2023-04-01',
    endDate: '2024-03-31',
    contactPerson: 'Robert Brown',
    contactPhone: '(555) 234-5678',
    coverageDetails: 'Senior care coverage with $300 deductible',
    isActive: true,
  },
];

export const mockCases: Case[] = [
  {
    id: uuidv4(),
    patientId: '1',
    patientName: 'John Doe',
    caseNumber: 'CASE-2023-001',
    title: 'Cardiac Evaluation',
    description: 'Patient admitted for cardiac evaluation and treatment',
    status: 'active',
    createdAt: '2023-01-15T09:30:00Z',
    updatedAt: '2023-06-20T14:45:00Z',
    insuranceId: mockInsurances[0].id,
    insuranceInfo: mockInsurances[0],
    assignedDoctorId: 'doc-001',
    assignedDoctorName: 'Dr. Emily Johnson',
    notes: 'Patient showing good progress after initial treatment',
    documents: [
      {
        id: uuidv4(),
        name: 'Initial Assessment',
        type: 'pdf',
        uploadDate: '2023-01-15T10:15:00Z',
        url: '/documents/initial-assessment.pdf',
      },
      {
        id: uuidv4(),
        name: 'ECG Results',
        type: 'pdf',
        uploadDate: '2023-01-16T11:30:00Z',
        url: '/documents/ecg-results.pdf',
      },
    ],
  },
  {
    id: uuidv4(),
    patientId: '2',
    patientName: 'Jane Smith',
    caseNumber: 'CASE-2023-002',
    title: 'Orthopedic Surgery',
    description: 'Patient scheduled for knee replacement surgery',
    status: 'pending',
    createdAt: '2023-02-10T13:45:00Z',
    updatedAt: '2023-06-15T09:20:00Z',
    insuranceId: mockInsurances[1].id,
    insuranceInfo: mockInsurances[1],
    assignedDoctorId: 'doc-002',
    assignedDoctorName: 'Dr. Michael Chen',
    notes: 'Pre-surgery assessment completed, awaiting insurance approval',
    documents: [
      {
        id: uuidv4(),
        name: 'X-Ray Results',
        type: 'jpg',
        uploadDate: '2023-02-10T14:30:00Z',
        url: '/documents/xray-results.jpg',
      },
    ],
  },
  {
    id: uuidv4(),
    patientId: '3',
    patientName: 'Robert Johnson',
    caseNumber: 'CASE-2023-003',
    title: 'Diabetes Management',
    description: 'Ongoing diabetes management and monitoring',
    status: 'active',
    createdAt: '2023-03-05T10:15:00Z',
    updatedAt: '2023-06-10T15:30:00Z',
    insuranceId: mockInsurances[2].id,
    insuranceInfo: mockInsurances[2],
    assignedDoctorId: 'doc-003',
    assignedDoctorName: 'Dr. Sarah Williams',
    notes: 'Blood sugar levels stabilizing with current medication regimen',
    documents: [
      {
        id: uuidv4(),
        name: 'Blood Work Results',
        type: 'pdf',
        uploadDate: '2023-03-06T09:45:00Z',
        url: '/documents/blood-work.pdf',
      },
      {
        id: uuidv4(),
        name: 'Nutrition Plan',
        type: 'docx',
        uploadDate: '2023-03-07T14:20:00Z',
        url: '/documents/nutrition-plan.docx',
      },
    ],
  },
  {
    id: uuidv4(),
    patientId: '4',
    patientName: 'Maria Garcia',
    caseNumber: 'CASE-2023-004',
    title: 'Pregnancy Care',
    description: 'Prenatal care and monitoring',
    status: 'active',
    createdAt: '2023-04-20T11:30:00Z',
    updatedAt: '2023-06-05T10:45:00Z',
    insuranceId: mockInsurances[3].id,
    insuranceInfo: mockInsurances[3],
    assignedDoctorId: 'doc-004',
    assignedDoctorName: 'Dr. Lisa Brown',
    notes: 'Pregnancy progressing normally, all tests within normal range',
    documents: [
      {
        id: uuidv4(),
        name: 'Ultrasound Results',
        type: 'jpg',
        uploadDate: '2023-04-21T13:15:00Z',
        url: '/documents/ultrasound.jpg',
      },
    ],
  },
  {
    id: uuidv4(),
    patientId: '5',
    patientName: 'William Davis',
    caseNumber: 'CASE-2023-005',
    title: 'Post-Surgery Recovery',
    description: 'Recovery monitoring after appendectomy',
    status: 'closed',
    createdAt: '2023-05-12T08:45:00Z',
    updatedAt: '2023-06-01T16:30:00Z',
    insuranceId: mockInsurances[4].id,
    insuranceInfo: mockInsurances[4],
    assignedDoctorId: 'doc-005',
    assignedDoctorName: 'Dr. James Wilson',
    notes: 'Patient fully recovered, case closed',
    documents: [
      {
        id: uuidv4(),
        name: 'Surgery Report',
        type: 'pdf',
        uploadDate: '2023-05-12T10:30:00Z',
        url: '/documents/surgery-report.pdf',
      },
      {
        id: uuidv4(),
        name: 'Discharge Summary',
        type: 'pdf',
        uploadDate: '2023-05-15T14:45:00Z',
        url: '/documents/discharge-summary.pdf',
      },
    ],
  },
]; 