export type IManagePatient = {
   id: number | string;
   phone_number: string;
   first_name: string;
   last_name: string;
   email: string;
   gender: string;
   date_of_birth: string;
};

export const managedPatients: IManagePatient[] = [
   {
      id: 1,
      first_name: 'Adrienne',
      last_name: 'Winckworth',
      email: 'awinckworth0@mediafire.com',
      gender: 'Female',
      phone_number: '+66 (453) 135-0752',
      date_of_birth: '01/02/1995',
   },
   {
      id: 2,
      first_name: 'Even',
      last_name: 'Greeding',
      email: 'egreeding1@flavors.me',
      gender: 'Male',
      phone_number: '+57 (101) 824-4679',
      date_of_birth: '11/21/1967',
   },
   {
      id: 3,
      first_name: 'Lyndsay',
      last_name: 'Caldero',
      email: 'lcaldero2@bloglines.com',
      gender: 'Female',
      phone_number: '+976 (799) 886-8384',
      date_of_birth: '09/08/1999',
   },
   {
      id: 4,
      first_name: 'Joya',
      last_name: 'Itzchaky',
      email: 'jitzchaky3@myspace.com',
      gender: 'Female',
      phone_number: '+855 (307) 640-1485',
      date_of_birth: '06/19/1961',
   },
   {
      id: 5,
      first_name: 'Aurea',
      last_name: 'Radborne',
      email: 'aradborne4@weather.com',
      gender: 'Female',
      phone_number: '+55 (431) 569-7820',
      date_of_birth: '04/03/1961',
   },
   {
      id: 6,
      first_name: 'Torey',
      last_name: 'Aspin',
      email: 'taspin5@sciencedirect.com',
      gender: 'Female',
      phone_number: '+351 (477) 491-2860',
      date_of_birth: '01/08/2010',
   },
   {
      id: 7,
      first_name: 'Augustine',
      last_name: 'Hengoed',
      email: 'ahengoed6@unesco.org',
      gender: 'Female',
      phone_number: '+86 (621) 875-3253',
      date_of_birth: '09/20/1989',
   },
   {
      id: 8,
      first_name: 'Allie',
      last_name: 'Brewett',
      email: 'abrewett7@cpanel.net',
      gender: 'Male',
      phone_number: '+351 (974) 808-5021',
      date_of_birth: '09/08/1963',
   },
   {
      id: 9,
      first_name: 'Uriah',
      last_name: 'Farnham',
      email: 'ufarnham8@behance.net',
      gender: 'Male',
      phone_number: '+7 (951) 252-0691',
      date_of_birth: '03/03/1985',
   },
   {
      id: 10,
      first_name: 'Mickey',
      last_name: 'Rekes',
      email: 'mrekes9@yandex.ru',
      gender: 'Male',
      phone_number: '+86 (395) 911-9803',
      date_of_birth: '11/27/1984',
   },
   {
      id: 11,
      first_name: 'Sibilla',
      last_name: 'Collingridge',
      email: 'scollingridgea@phoca.cz',
      gender: 'Female',
      phone_number: '+86 (785) 896-3295',
      date_of_birth: '05/24/2008',
   },
   {
      id: 12,
      first_name: 'Evelin',
      last_name: 'Deeney',
      email: 'edeeneyb@mapy.cz',
      gender: 'Male',
      phone_number: '+86 (145) 981-2145',
      date_of_birth: '06/08/2007',
   },
   {
      id: 13,
      first_name: 'Lea',
      last_name: 'Liveley',
      email: 'lliveleyc@hp.com',
      gender: 'Female',
      phone_number: '+509 (208) 720-2449',
      date_of_birth: '05/06/2015',
   },
   {
      id: 14,
      first_name: 'Duane',
      last_name: 'Tremberth',
      email: 'dtremberthd@twitter.com',
      gender: 'Male',
      phone_number: '+380 (573) 104-1660',
      date_of_birth: '03/05/1990',
   },
   {
      id: 15,
      first_name: 'Dallon',
      last_name: 'Careless',
      email: 'dcarelesse@ifeng.com',
      gender: 'Male',
      phone_number: '+63 (915) 456-7550',
      date_of_birth: '09/09/2002',
   },
   {
      id: 16,
      first_name: 'Colby',
      last_name: 'Corten',
      email: 'ccortenf@archive.org',
      gender: 'Male',
      phone_number: '+685 (987) 108-8080',
      date_of_birth: '12/29/2005',
   },
   {
      id: 17,
      first_name: 'Gunther',
      last_name: 'Beggin',
      email: 'gbegging@vistaprint.com',
      gender: 'Male',
      phone_number: '+62 (836) 810-4398',
      date_of_birth: '04/11/1994',
   },
   {
      id: 18,
      first_name: 'Johnna',
      last_name: 'Hargreves',
      email: 'jhargrevesh@google.es',
      gender: 'Female',
      phone_number: '+380 (284) 861-4952',
      date_of_birth: '01/22/2015',
   },
   {
      id: 19,
      first_name: 'Saul',
      last_name: 'Nolleth',
      email: 'snollethi@apple.com',
      gender: 'Male',
      phone_number: '+420 (708) 986-3343',
      date_of_birth: '01/10/1997',
   },
   {
      id: 20,
      first_name: 'Maryrose',
      last_name: 'Thonason',
      email: 'mthonasonj@fema.gov',
      gender: 'Female',
      phone_number: '+355 (223) 310-8043',
      date_of_birth: '07/11/1960',
   },
];
