export const paths = Object.freeze({
   app: '/',
   login: '/login',
   auth: '/auth',
   cubex: '/cubex',
   multistepForm: '/cubex/multistep-form',
   patientList: '/cubex/patient-list',
   patientAppointment: '/cubex/patient-appointment',
   hospitalAppointment: '/cubex/hospital-appointment',
   patientManagement: '/cubex/patient-management',
   personnelManagement: '/cubex/personnel-management',
   insuranceInformation: '/cubex/insurance-information',
   patientDashboard: '/cubex/patient-dashboard',
   waitingBoard: '/cubex/waiting-board',
   agenda: '/cubex/agenda',
   laboratoryAnalysis: '/cubex/laboratory-analysis',
   treatmentDocumentation: '/cubex/treatment-documentation',
   medicationManagement: '/cubex/medication-management',
   medicationInventory: '/cubex/medication-inventory',
   taskManagement: '/cubex/task-management',
   taskView: '/cubex/task-management/view/:task_id',
   taskCreate: '/cubex/task-management/create',
   userActivity: '/cubex/user-activity',
   templateView: '/cubex/template-management/view/:template_id',
});
