export const agendas = [
   {
      time: '11:07',
      task: 'consultation',
      doctor: 'Gardie Dinse',
      patient: 'Lindsey Greenhalgh',
      outcome: 'stable',
   },
   {
      time: '8:31',
      task: 'checkup',
      doctor: 'Eulalie Inglese',
      patient: 'Damita Woolstenholmes',
      outcome: 'stable',
   },
   {
      time: '10:02',
      task: 'checkup',
      doctor: 'Caspar Anniwell',
      patient: 'Adora Everall',
      outcome: 'deteriorated',
   },
   {
      time: '10:51',
      task: 'treatment',
      doctor: 'Tiff Keeble',
      patient: 'Jerad Glentz',
      outcome: 'stable',
   },
   {
      time: '8:57',
      task: 'treatment',
      doctor: 'Kristi Gewer',
      patient: 'Berkeley Maryott',
      outcome: 'deteriorated',
   },
   {
      time: '9:59',
      task: 'consultation',
      doctor: 'Renato Balas',
      patient: 'Darcey Glanders',
      outcome: 'recovered',
   },
   {
      time: '10:50',
      task: 'consultation',
      doctor: 'Antonius Surgener',
      patient: 'Zita Sturrock',
      outcome: 'stable',
   },
   {
      time: '8:55',
      task: 'consultation',
      doctor: 'Kevin Wadlow',
      patient: 'Stephi Turnbull',
      outcome: 'recovered',
   },
   {
      time: '10:17',
      task: 'consultation',
      doctor: 'Laurella Gerdes',
      patient: "Sharity O'Scandall",
      outcome: 'recovered',
   },
   {
      time: '9:16',
      task: 'consultation',
      doctor: 'Ailene Simnett',
      patient: 'Janeta Abrahm',
      outcome: 'deteriorated',
   },
   {
      time: '9:02',
      task: 'treatment',
      doctor: 'Reagen Trussler',
      patient: 'Leonhard Kick',
      outcome: 'recovered',
   },
   {
      time: '11:39',
      task: 'checkup',
      doctor: 'Megan Curragh',
      patient: 'Bran Eannetta',
      outcome: 'deteriorated',
   },
   {
      time: '11:07',
      task: 'surgery',
      doctor: 'Kalina Berfoot',
      patient: 'Neddy Varfalameev',
      outcome: 'stable',
   },
   {
      time: '10:04',
      task: 'surgery',
      doctor: 'Consalve Godridge',
      patient: 'Celesta Hunday',
      outcome: 'stable',
   },
   {
      time: '11:46',
      task: 'treatment',
      doctor: 'Evin Allcock',
      patient: 'Erv De Ruggero',
      outcome: 'recovered',
   },
   {
      time: '11:58',
      task: 'consultation',
      doctor: 'Petronilla Joannidi',
      patient: 'Rolf Persian',
      outcome: 'deteriorated',
   },
   {
      time: '9:30',
      task: 'treatment',
      doctor: 'Orelee Thebeaud',
      patient: 'Durand Fargie',
      outcome: 'stable',
   },
   {
      time: '8:56',
      task: 'surgery',
      doctor: 'Willie Clay',
      patient: 'Cad Eynon',
      outcome: 'recovered',
   },
   {
      time: '9:31',
      task: 'checkup',
      doctor: 'Candis Budik',
      patient: 'Hugo Carillo',
      outcome: 'recovered',
   },
];
