export type IManagedDoctor = {
   id: string;
   firstName: string;
   lastName: string;
   gender: 'Female' | 'Male';
   specialization: string;
   locations: string[];
   hireDate: string;
   salary: number;
   yearsOfExperience: number;
};

export type IManagedNurse = {
   id: string;
   firstName: string;
   lastName: string;
   gender: 'Female' | 'Male';
   rank: string;
   department: string;
   location: string;
   hireDate: string;
   salary: number;
   yearsOfExperience: number;
};

export type IManagedOther = {
   id: string;
   firstName: string;
   lastName: string;
   gender: 'Female' | 'Male';
   role: string;
   department: string;
   location: string;
   hireDate: string;
   salary: number;
   yearsOfExperience: number;
   shift: 'Morning' | 'Afternoon' | 'Night';
};

export const managedDoctors: IManagedDoctor[] = [
   {
      id: '01HXEA1QX8RZSWP8W24VXQNZH0',
      firstName: 'Kathleen',
      lastName: 'Twidle',
      gender: 'Female',
      specialization: 'Pediatrics',
      locations: ['Arkansas Hospital'],
      hireDate: '03/11/2014',
      salary: 75774.16,
      yearsOfExperience: 32,
   },
   {
      id: '01HXEA1QXHK9YNT30MDN15WS52',
      firstName: 'Marnia',
      lastName: 'Dohrmann',
      gender: 'Female',
      specialization: 'Urology',
      locations: ['Doe Crossing Hospital'],
      hireDate: '11/13/2023',
      salary: 30011.5,
      yearsOfExperience: 2,
   },
   {
      id: '01HXEA1QXKGCKV1XSZ8CFPAMF9',
      firstName: 'Vita',
      lastName: 'Kermitt',
      gender: 'Female',
      specialization: 'Psychiatry',
      locations: ['Arizona Hospital', 'Roth Hospital', 'Clemons Hospital'],
      hireDate: '11/18/2000',
      salary: 149247.27,
      yearsOfExperience: 41,
   },
   {
      id: '01HXEA1QXN0C641QHBY5MFBZ4H',
      firstName: 'Domini',
      lastName: 'Kelbie',
      gender: 'Female',
      specialization: 'Dermatology',
      locations: ['Ridge Oak Hospital', 'Coleman Hospital', 'Hanover Hospital'],
      hireDate: '03/05/2006',
      salary: 180318.69,
      yearsOfExperience: 37,
   },
   {
      id: '01HXEA1QXQ3NTSESAHNDAC880A',
      firstName: 'Krystle',
      lastName: 'Dursley',
      gender: 'Female',
      specialization: 'Urology',
      locations: ['Laurel Hospital'],
      hireDate: '05/26/2016',
      salary: 118212.52,
      yearsOfExperience: 22,
   },
   {
      id: '01HXEA1QXR68SDYRM5XDQD23VW',
      firstName: 'Lauren',
      lastName: 'Decourt',
      gender: 'Female',
      specialization: 'Cardiology',
      locations: ['Carpenter Hospital', 'Coolidge Hospital'],
      hireDate: '03/05/2021',
      salary: 108198.64,
      yearsOfExperience: 10,
   },
   {
      id: '01HXEA1QXT5088S6SY9XFBXQ76',
      firstName: 'Kristoffer',
      lastName: 'Ashlin',
      gender: 'Male',
      specialization: 'Psychiatry',
      locations: ['Donald Hospital'],
      hireDate: '10/02/2006',
      salary: 128230.16,
      yearsOfExperience: 32,
   },
   {
      id: '01HXEA1QXVGRNRWSNRXN1PYXKZ',
      firstName: 'Wells',
      lastName: 'Brum',
      gender: 'Male',
      specialization: 'Gastroenterology',
      locations: ['Sunnyside Hospital', 'Scofield Hospital', 'Reindahl Hospital'],
      hireDate: '07/06/2000',
      salary: 69881.61,
      yearsOfExperience: 42,
   },
   {
      id: '01HXEA1QXX0MKZVFPBK25TQ82X',
      firstName: 'Helli',
      lastName: 'Uzzell',
      gender: 'Female',
      specialization: 'Dermatology',
      locations: ['Morrow Hospital', 'Kipling Hospital'],
      hireDate: '09/26/2015',
      salary: 73991.35,
      yearsOfExperience: 26,
   },
   {
      id: '01HXEA1QXZEQ61EH6BGPYGSGEZ',
      firstName: 'Dianne',
      lastName: 'Shutle',
      gender: 'Female',
      specialization: 'Neurology',
      locations: ['Armistice Hospital', 'Mayfield Hospital'],
      hireDate: '09/19/2021',
      salary: 87321.63,
      yearsOfExperience: 34,
   },
   {
      id: '01HXEA1QY0FACFSHE8X4T7TTGV',
      firstName: 'Cristy',
      lastName: 'Jaspar',
      gender: 'Female',
      specialization: 'Cardiology',
      locations: ['John Wall Hospital'],
      hireDate: '12/28/2021',
      salary: 185899.62,
      yearsOfExperience: 41,
   },
   {
      id: '01HXEA1QY12N7NSZ90R6FD633J',
      firstName: 'Muriel',
      lastName: 'Scates',
      gender: 'Female',
      specialization: 'Oncology',
      locations: ['International Hospital', 'Ruskin Hospital', 'Nancy Hospital'],
      hireDate: '08/06/2004',
      salary: 190303.54,
      yearsOfExperience: 3,
   },
   {
      id: '01HXEA1QY3WS1T1GKT49XX6TV8',
      firstName: 'Langsdon',
      lastName: 'Kienle',
      gender: 'Male',
      specialization: 'Psychiatry',
      locations: ['Sycamore Hospital', 'Union Hospital'],
      hireDate: '12/03/2004',
      salary: 194623.39,
      yearsOfExperience: 14,
   },
   {
      id: '01HXEA1QY4QDTQBDX8CSEK54P2',
      firstName: 'Brock',
      lastName: 'Stanbridge',
      gender: 'Male',
      specialization: 'Psychiatry',
      locations: ['Tomscot Hospital'],
      hireDate: '02/17/2021',
      salary: 120791.67,
      yearsOfExperience: 9,
   },
   {
      id: '01HXEA1QY59KM3KSQSB5H4FH37',
      firstName: 'Emmett',
      lastName: 'Tallet',
      gender: 'Male',
      specialization: 'Urology',
      locations: ['Crest Line Hospital'],
      hireDate: '07/01/2011',
      salary: 115767.72,
      yearsOfExperience: 4,
   },
   {
      id: '01HXEA1QY7HAXZHTHB4N29JCSF',
      firstName: 'Marybelle',
      lastName: 'Osgorby',
      gender: 'Female',
      specialization: 'Oncology',
      locations: ['Westerfield Hospital'],
      hireDate: '04/12/2009',
      salary: 66237.02,
      yearsOfExperience: 40,
   },
   {
      id: '01HXEA1QY8EQZSWMKQ8600B79R',
      firstName: 'Coleman',
      lastName: 'Chatterton',
      gender: 'Male',
      specialization: 'Cardiology',
      locations: ['Forest Dale Hospital'],
      hireDate: '12/17/2012',
      salary: 199282.71,
      yearsOfExperience: 47,
   },
   {
      id: '01HXEA1QY92KTQM5P4CRPVYRCD',
      firstName: 'Aymer',
      lastName: 'Rivard',
      gender: 'Male',
      specialization: 'Dermatology',
      locations: ['Anthes Hospital', 'Linden Hospital', 'Lindbergh Hospital'],
      hireDate: '02/11/2001',
      salary: 111249.53,
      yearsOfExperience: 30,
   },
   {
      id: '01HXEA1QYAACCR44F6RX1YBQCM',
      firstName: 'Twila',
      lastName: 'Poone',
      gender: 'Female',
      specialization: 'Psychiatry',
      locations: ['Basil Hospital', 'Fieldstone Hospital', 'Blue Bill Park Hospital'],
      hireDate: '02/07/2013',
      salary: 175004.42,
      yearsOfExperience: 46,
   },
   {
      id: '01HXEA1QYCSQZT9MESQ6NVQ9HH',
      firstName: 'Cassandre',
      lastName: 'Saunder',
      gender: 'Female',
      specialization: 'Orthopedics',
      locations: ['Oneill Hospital', 'Golf View Hospital', 'Jana Hospital'],
      hireDate: '01/22/2010',
      salary: 74049.62,
      yearsOfExperience: 46,
   },
   {
      id: '01HXEA1QYDV1454XV7ZW15317W',
      firstName: 'Leonid',
      lastName: 'Slyne',
      gender: 'Male',
      specialization: 'Neurology',
      locations: ['Coolidge Hospital', 'Di Loreto Hospital'],
      hireDate: '02/28/2018',
      salary: 143860.31,
      yearsOfExperience: 18,
   },
   {
      id: '01HXEA1QYFKYFHRSP2NVKZM51Y',
      firstName: 'Bree',
      lastName: 'Ritmeier',
      gender: 'Female',
      specialization: 'Endocrinology',
      locations: ['Brown Hospital', 'Myrtle Hospital'],
      hireDate: '11/24/2012',
      salary: 66999.3,
      yearsOfExperience: 43,
   },
   {
      id: '01HXEA1QYHS8JEA06Z9CFVBC97',
      firstName: 'Ashlan',
      lastName: 'Papps',
      gender: 'Female',
      specialization: 'Urology',
      locations: ['Blue Bill Park Hospital', 'Sommers Hospital'],
      hireDate: '02/16/2020',
      salary: 174506.76,
      yearsOfExperience: 33,
   },
   {
      id: '01HXEA1QYJH9D2NZVE9RFZGX4R',
      firstName: 'Broderick',
      lastName: 'Tantrum',
      gender: 'Male',
      specialization: 'Urology',
      locations: ['Aberg Hospital', 'Sunbrook Hospital', '3rd Hospital'],
      hireDate: '12/22/2015',
      salary: 45212.95,
      yearsOfExperience: 23,
   },
   {
      id: '01HXEA1QYKP57Z2W1BTC8Q1ZQ4',
      firstName: 'Lyn',
      lastName: 'Housley',
      gender: 'Male',
      specialization: 'Endocrinology',
      locations: ['Blackbird Hospital', 'Stuart Hospital'],
      hireDate: '08/05/2019',
      salary: 159694.29,
      yearsOfExperience: 38,
   },
];

export const managedNurses: IManagedNurse[] = [
   {
      id: '01HXEAFA3N09YXVADXR2D1P13B',
      firstName: 'Dotti',
      lastName: 'Beteriss',
      gender: 'Female',
      rank: 'RN',
      department: 'ICU',
      location: 'Quincy',
      hireDate: '02/07/2008',
      salary: 44566.78,
      yearsOfExperience: 42,
   },
   {
      id: '01HXEAFA3TW8TY6D2X3TXBQW14',
      firstName: 'Helen',
      lastName: 'Cicculi',
      gender: 'Female',
      rank: 'CNA',
      department: 'Emergency',
      location: 'Ryan',
      hireDate: '01/22/2016',
      salary: 63324.14,
      yearsOfExperience: 47,
   },
   {
      id: '01HXEAFA3XQJX5V70HWTS7GHBH',
      firstName: 'Karin',
      lastName: 'Fantonetti',
      gender: 'Female',
      rank: 'NCS',
      department: 'ICU',
      location: 'Atwood',
      hireDate: '06/19/2021',
      salary: 145450.07,
      yearsOfExperience: 21,
   },
   {
      id: '01HXEAFA3Z2T4AX5EYNFAF15YD',
      firstName: 'Ricki',
      lastName: 'Southern',
      gender: 'Female',
      rank: 'CNA',
      department: 'ICU',
      location: 'Springview',
      hireDate: '09/12/2009',
      salary: 32544.7,
      yearsOfExperience: 5,
   },
   {
      id: '01HXEAFA4438X15AKEZWYNV0VX',
      firstName: 'Townie',
      lastName: 'Bakeup',
      gender: 'Male',
      rank: 'CNA',
      department: 'ICU',
      location: 'Kennedy',
      hireDate: '11/29/2021',
      salary: 129547.62,
      yearsOfExperience: 40,
   },
   {
      id: '01HXEAFA47FMDNQN5QQZPEN2VM',
      firstName: 'Daria',
      lastName: 'Bottrill',
      gender: 'Female',
      rank: 'NCS',
      department: 'Surgery',
      location: 'Schiller',
      hireDate: '04/02/2007',
      salary: 37107.4,
      yearsOfExperience: 15,
   },
   {
      id: '01HXEAFA4982KCGHVG08Y001C4',
      firstName: 'Read',
      lastName: 'Mico',
      gender: 'Male',
      rank: 'APRN',
      department: 'Emergency',
      location: 'Eagan',
      hireDate: '01/15/2004',
      salary: 137081.97,
      yearsOfExperience: 38,
   },
   {
      id: '01HXEAFA4B5C2VAQNA6FDKHEJN',
      firstName: 'Travis',
      lastName: 'Ledner',
      gender: 'Male',
      rank: 'RN',
      department: 'Surgery',
      location: 'Carioca',
      hireDate: '05/31/2014',
      salary: 37120.16,
      yearsOfExperience: 12,
   },
   {
      id: '01HXEAFA4DGJJNAJ4XM68ZQ1V5',
      firstName: 'Doloritas',
      lastName: 'Pfaffel',
      gender: 'Female',
      rank: 'APRN',
      department: 'ICU',
      location: 'Donald',
      hireDate: '10/08/2011',
      salary: 147159.83,
      yearsOfExperience: 50,
   },
   {
      id: '01HXEAFA4FXAHDN2M1A4CYH5PM',
      firstName: 'Maddi',
      lastName: 'Tremblay',
      gender: 'Female',
      rank: 'LPN',
      department: 'ICU',
      location: 'Oxford',
      hireDate: '08/31/2020',
      salary: 94028.03,
      yearsOfExperience: 31,
   },
   {
      id: '01HXEAFA4HHV2289YS8WGTGFX8',
      firstName: 'Hanny',
      lastName: 'Paddy',
      gender: 'Female',
      rank: 'CNA',
      department: 'ICU',
      location: 'Toban',
      hireDate: '12/16/2021',
      salary: 142860.09,
      yearsOfExperience: 42,
   },
   {
      id: '01HXEAFA4K8PAYKKBXFWF7B1C6',
      firstName: 'Sauncho',
      lastName: 'Kupis',
      gender: 'Male',
      rank: 'NCS',
      department: 'ICU',
      location: 'Washington',
      hireDate: '09/11/2008',
      salary: 49261.53,
      yearsOfExperience: 28,
   },
   {
      id: '01HXEAFA4NDCN0GQ31HBM9BZNG',
      firstName: 'Ariel',
      lastName: 'Leppo',
      gender: 'Male',
      rank: 'NCS',
      department: 'Surgery',
      location: 'Butterfield',
      hireDate: '09/20/2004',
      salary: 120772.31,
      yearsOfExperience: 49,
   },
   {
      id: '01HXEAFA4QXN194D44N78ETZ4R',
      firstName: 'Kylen',
      lastName: 'Burdfield',
      gender: 'Female',
      rank: 'RN',
      department: 'Surgery',
      location: 'Nelson',
      hireDate: '03/16/2018',
      salary: 51177.22,
      yearsOfExperience: 45,
   },
   {
      id: '01HXEAFA4SWKHCV1B32T17V2CH',
      firstName: 'Clair',
      lastName: 'Milne',
      gender: 'Male',
      rank: 'APRN',
      department: 'Surgery',
      location: 'Cambridge',
      hireDate: '02/25/2020',
      salary: 136700.26,
      yearsOfExperience: 3,
   },
   {
      id: '01HXEAFA4WHX1BSWNS1H94JPVN',
      firstName: 'Nikolos',
      lastName: 'Heape',
      gender: 'Male',
      rank: 'CNA',
      department: 'Surgery',
      location: 'Porter',
      hireDate: '06/10/2002',
      salary: 58864.32,
      yearsOfExperience: 27,
   },
   {
      id: '01HXEAFA4YH4RRB4DHBDC4HCHK',
      firstName: 'Luciana',
      lastName: 'Gore',
      gender: 'Female',
      rank: 'NCS',
      department: 'Emergency',
      location: 'Becker',
      hireDate: '03/18/2008',
      salary: 129384.65,
      yearsOfExperience: 7,
   },
   {
      id: '01HXEAFA50SPCRP9CTVNVA3GVX',
      firstName: 'Cally',
      lastName: 'Nardrup',
      gender: 'Female',
      rank: 'NCS',
      department: 'Emergency',
      location: 'Raven',
      hireDate: '01/24/2022',
      salary: 104358.89,
      yearsOfExperience: 33,
   },
   {
      id: '01HXEAFA52786NR3G10Y44N7PF',
      firstName: 'Mandy',
      lastName: 'Fison',
      gender: 'Female',
      rank: 'NCS',
      department: 'Surgery',
      location: 'Maryland',
      hireDate: '12/31/2000',
      salary: 78237.32,
      yearsOfExperience: 9,
   },
   {
      id: '01HXEAFA540B4MRVJZS1FA2313',
      firstName: 'Renae',
      lastName: 'Mayte',
      gender: 'Female',
      rank: 'NCS',
      department: 'ICU',
      location: 'Dakota',
      hireDate: '11/14/2017',
      salary: 110228.64,
      yearsOfExperience: 30,
   },
   {
      id: '01HXEAFA563BZ5VD6SDQDCJ0XK',
      firstName: 'Vita',
      lastName: 'Stonuary',
      gender: 'Female',
      rank: 'RN',
      department: 'ICU',
      location: 'Mayer',
      hireDate: '05/27/2016',
      salary: 52955.45,
      yearsOfExperience: 3,
   },
   {
      id: '01HXEAFA58KZD0BCM9MWT48VBG',
      firstName: 'Hester',
      lastName: 'Garron',
      gender: 'Female',
      rank: 'RN',
      department: 'Emergency',
      location: 'Melby',
      hireDate: '02/03/2012',
      salary: 54785.79,
      yearsOfExperience: 35,
   },
   {
      id: '01HXEAFA5A587A5SMB0E54ZN6A',
      firstName: 'Giffy',
      lastName: 'Doers',
      gender: 'Male',
      rank: 'APRN',
      department: 'Emergency',
      location: 'Muir',
      hireDate: '05/12/2006',
      salary: 36282.48,
      yearsOfExperience: 6,
   },
   {
      id: '01HXEAFA5CR20K7DQ4TPZFPXSH',
      firstName: 'Antonie',
      lastName: 'Crumpton',
      gender: 'Female',
      rank: 'APRN',
      department: 'Emergency',
      location: 'Havey',
      hireDate: '09/16/2003',
      salary: 43163.35,
      yearsOfExperience: 5,
   },
   {
      id: '01HXEAFA5EX3BCAMDM6CKFVCH9',
      firstName: 'Culley',
      lastName: 'Pembery',
      gender: 'Male',
      rank: 'APRN',
      department: 'Surgery',
      location: 'Russell',
      hireDate: '02/08/2019',
      salary: 66064.73,
      yearsOfExperience: 11,
   },
];

export const managedOthers: IManagedOther[] = [
   {
      id: '01HXEB24893B2WSW8EYCY1AHEH',
      firstName: 'Rodge',
      lastName: 'Laydel',
      gender: 'Male',
      role: 'Security Guard',
      department: 'Maintenance',
      location: 'Vera',
      hireDate: '06/26/2012',
      salary: 114794.59,
      yearsOfExperience: 25,
      shift: 'Afternoon',
   },
   {
      id: '01HXEB248BG61EZTZHMXGYA09W',
      firstName: 'Gwendolen',
      lastName: 'Doll',
      gender: 'Female',
      role: 'Receptionist',
      department: 'Maintenance',
      location: 'Riverside',
      hireDate: '12/22/2014',
      salary: 103412.44,
      yearsOfExperience: 35,
      shift: 'Morning',
   },
   {
      id: '01HXEB248D4076T1W1Y1QGTWRM',
      firstName: 'Jyoti',
      lastName: 'Eaglen',
      gender: 'Female',
      role: 'Janitor',
      department: 'Maintenance',
      location: 'Pine View',
      hireDate: '12/23/2018',
      salary: 99485.56,
      yearsOfExperience: 41,
      shift: 'Morning',
   },
   {
      id: '01HXEB248E0VP25GGDPCHTZF40',
      firstName: 'Cecil',
      lastName: 'Salerg',
      gender: 'Male',
      role: 'Receptionist',
      department: 'IT',
      location: '2nd',
      hireDate: '11/04/2012',
      salary: 34363.4,
      yearsOfExperience: 44,
      shift: 'Morning',
   },
   {
      id: '01HXEB248FZ0MVDZV0FHE9XC5V',
      firstName: 'Ruby',
      lastName: 'Nazaret',
      gender: 'Male',
      role: 'Receptionist',
      department: 'IT',
      location: 'Cody',
      hireDate: '03/18/2018',
      salary: 127370.88,
      yearsOfExperience: 9,
      shift: 'Night',
   },
   {
      id: '01HXEB248GGEC38FA8X5YAJMYZ',
      firstName: 'Dawn',
      lastName: 'Inwood',
      gender: 'Female',
      role: 'Janitor',
      department: 'Administration',
      location: 'Arkansas',
      hireDate: '01/01/2018',
      salary: 138483.57,
      yearsOfExperience: 36,
      shift: 'Night',
   },
   {
      id: '01HXEB248HVW1DBPXSXENY82RP',
      firstName: 'Jeanelle',
      lastName: 'Blenkharn',
      gender: 'Female',
      role: 'Security Guard',
      department: 'Security',
      location: 'Evergreen',
      hireDate: '11/04/2021',
      salary: 41262.88,
      yearsOfExperience: 46,
      shift: 'Afternoon',
   },
   {
      id: '01HXEB248K34X9FQ19BBXEW6YR',
      firstName: 'Uriah',
      lastName: 'Smartman',
      gender: 'Male',
      role: 'Receptionist',
      department: 'Maintenance',
      location: 'School',
      hireDate: '06/29/2021',
      salary: 112591.71,
      yearsOfExperience: 23,
      shift: 'Morning',
   },
   {
      id: '01HXEB248MWDNXCAJYWWK39VGE',
      firstName: 'Nilson',
      lastName: 'Titman',
      gender: 'Male',
      role: 'IT Support',
      department: 'Security',
      location: 'Mallory',
      hireDate: '01/26/2009',
      salary: 52166.32,
      yearsOfExperience: 18,
      shift: 'Afternoon',
   },
   {
      id: '01HXEB248PP7M7WP8E91WPZW8Z',
      firstName: 'Emmanuel',
      lastName: 'Vanlint',
      gender: 'Male',
      role: 'Receptionist',
      department: 'IT',
      location: 'Thackeray',
      hireDate: '01/02/2022',
      salary: 45355.25,
      yearsOfExperience: 40,
      shift: 'Night',
   },
   {
      id: '01HXEB248TVJ49J5YFMAG87H64',
      firstName: 'Mikaela',
      lastName: 'McGahey',
      gender: 'Female',
      role: 'Security Guard',
      department: 'Security',
      location: 'Hayes',
      hireDate: '01/12/2015',
      salary: 47152.44,
      yearsOfExperience: 39,
      shift: 'Afternoon',
   },
   {
      id: '01HXEB248X4DK3ZG3W3X9VH7ED',
      firstName: 'Fawn',
      lastName: 'Mark',
      gender: 'Female',
      role: 'Receptionist',
      department: 'Maintenance',
      location: 'North',
      hireDate: '12/02/2008',
      salary: 85759.46,
      yearsOfExperience: 20,
      shift: 'Night',
   },
];
