export enum IPages {
   DASHBOARD = 'Dashboard',
   MULTISTEP_FORM = 'Multistep Form',
   PATIENT_LIST = 'Patient List',
   PATIENT_APPOINTMENT = 'Patient Appointment',
   HOSPITAL_APPOINTMENT = 'Hospital Appointment',
   PATIENT_MANAGEMENT = 'Patient Management',
   PERSONNEL_MANAGEMENT = 'Personnel Management',
   INSURANCE_INFORMATION = 'Insurance Information',
   PATIENT_DASHBOARD = 'Patient Dashboard',
   WAITING_BOARD = 'Waiting Board',
   AGENDA = 'Agenda',
   LABORATORY_ANALYSIS = 'Laboratory Analysis',
   TREATMENT_DOCUMENTATION = 'Treatment Documentation',
   MEDICATION_MANAGEMENT = 'Medication Management',
   MEDICATION_INVENTORY = 'Medication Inventory',
   TASK_MANAGEMENT = 'Task Management',
   USER_ACTIVITY = 'User Activity',
   TEMPLATE_MANAGEMENT = 'Template Management',
   TEMPLATE_VIEW = 'Template View',
   EMAIL = 'Email',
   BILLING = 'Billing',
   PATIENT_HISTORY = 'Patient History',
   SURVEY = 'Survey',
}

export type SetState<T> = React.Dispatch<React.SetStateAction<T>>;
