// import { FormBuilderPostData } from 'react-form-builder2';

export const TEMPLATE_MANAGEMENT_MOCK = {
   task_data: [
      {
         id: '4E995CAC-4EE1-4C3A-A3D0-D4FA4F5C839F',
         element: 'Header',
         text: 'Header Text',
         static: true,
         required: false,
         bold: false,
         italic: false,
         content: '<strong>Medical Invoce</strong> ',
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         dirty: false,
      },
      {
         id: '62A0FFE9-D5E7-4807-9800-A66422B90159',
         element: 'TwoColumnRow',
         text: 'Two Column Row',
         required: false,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'two_col_row_2886D456-D562-400C-9745-C5B9820F8C31',
         childItems: ['D631F8FE-1167-461B-9783-E1CBD6EDBDF9', 'EE86C84B-2563-440B-844E-DF6DEAE5867C'],
         isContainer: true,
      },
      {
         id: 'EB47DB8C-C8D3-4742-83C2-63F0DBBD9E8C',
         element: 'TwoColumnRow',
         text: 'Two Column Row',
         required: false,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'two_col_row_40BF196C-3C46-40A6-889F-1AD3240CB7B7',
         childItems: ['4162E078-50E0-4860-9EB8-E568F52B5CB1', 'B3FCAE11-DB69-4298-8DF8-5DFD8F718810'],
         isContainer: true,
      },
      {
         id: 'AB552FAB-3E29-4158-BD5A-08FC1407C99D',
         element: 'TwoColumnRow',
         text: 'Two Column Row',
         required: false,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'two_col_row_973BC1BC-B0FF-490A-96D8-E6542CD8836A',
         childItems: ['85A5C441-4223-4294-92F3-AF071FD38742', '6E64699D-091F-49F2-B78B-723DB3A10951'],
         isContainer: true,
      },
      {
         id: '7D8F4683-C364-41F4-9352-D49782242456',
         element: 'TextArea',
         text: 'Multi-line Input',
         required: false,
         canHaveAnswer: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'text_area_DF64CF39-EBB8-4A46-8163-F0CA3C40774A',
         label: 'Provided services ',
         dirty: false,
      },
      {
         id: '3D725235-DAEC-4AE3-94EA-6C2E72D3A7BD',
         element: 'TwoColumnRow',
         text: 'Two Column Row',
         required: false,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'two_col_row_BD89FB0E-B42A-425A-9B60-1AD410D9D3E0',
         childItems: ['0ABEB4FD-16CC-47C6-A6A4-ADB8F1622625', 'A04A6D0C-F85A-4AC7-957C-28A22118E6EF'],
         isContainer: true,
      },
      {
         id: '0ABEB4FD-16CC-47C6-A6A4-ADB8F1622625',
         element: 'DatePicker',
         text: 'Date',
         required: false,
         readOnly: false,
         defaultToday: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         dateFormat: 'MM/dd/yyyy',
         timeFormat: 'hh:mm aa',
         showTimeSelect: false,
         showTimeSelectOnly: false,
         showTimeInput: false,
         field_name: 'date_picker_298A62F7-2C3A-4024-9C9B-74EF80D495A1',
         label: 'Date ',
         dirty: false,
         col: 0,
         parentId: '3D725235-DAEC-4AE3-94EA-6C2E72D3A7BD',
         parentIndex: 6,
      },
      {
         id: 'A04A6D0C-F85A-4AC7-957C-28A22118E6EF',
         element: 'NumberInput',
         text: 'Number Input',
         required: false,
         canHaveAnswer: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'number_input_5ABD7AFF-8E81-49D1-A0B2-0AC6AC628BB8',
         label: 'Total amount ',
         dirty: false,
         col: 1,
         parentId: '3D725235-DAEC-4AE3-94EA-6C2E72D3A7BD',
         parentIndex: 13,
      },
      {
         id: 'D631F8FE-1167-461B-9783-E1CBD6EDBDF9',
         element: 'Label',
         text: 'Label',
         static: true,
         required: false,
         bold: false,
         italic: false,
         content: '<strong>Patient Information</strong> ',
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         col: 0,
         parentId: '62A0FFE9-D5E7-4807-9800-A66422B90159',
         parentIndex: 1,
         dirty: false,
      },
      {
         id: 'EE86C84B-2563-440B-844E-DF6DEAE5867C',
         element: 'Label',
         text: 'Label',
         static: true,
         required: false,
         bold: false,
         italic: false,
         content: '<strong>Prescribing Physicians Information</strong> ',
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         col: 1,
         parentId: '62A0FFE9-D5E7-4807-9800-A66422B90159',
         parentIndex: 1,
         dirty: false,
      },
      {
         id: '4162E078-50E0-4860-9EB8-E568F52B5CB1',
         element: 'TextInput',
         text: 'Text Input',
         required: false,
         canHaveAnswer: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'text_input_6EC18E42-1E4C-43D7-80A5-782511087B7F',
         label: 'Name and surname ',
         col: 0,
         parentId: 'EB47DB8C-C8D3-4742-83C2-63F0DBBD9E8C',
         parentIndex: 2,
         dirty: false,
      },
      {
         id: 'B3FCAE11-DB69-4298-8DF8-5DFD8F718810',
         element: 'TextInput',
         text: 'Text Input',
         required: false,
         canHaveAnswer: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'text_input_227FC570-A207-4648-B038-7F252913059F',
         label: 'Name and surname ',
         col: 1,
         parentId: 'EB47DB8C-C8D3-4742-83C2-63F0DBBD9E8C',
         parentIndex: 2,
         dirty: false,
      },
      {
         id: '85A5C441-4223-4294-92F3-AF071FD38742',
         element: 'PhoneNumber',
         text: 'Phone Number',
         required: false,
         canHaveAnswer: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'phone_input_516895B2-EB6A-414C-A542-004F1CCDA7F8',
         label: 'Phone Number',
         col: 0,
         parentId: 'AB552FAB-3E29-4158-BD5A-08FC1407C99D',
         parentIndex: 3,
      },
      {
         id: '6E64699D-091F-49F2-B78B-723DB3A10951',
         element: 'PhoneNumber',
         text: 'Phone Number',
         required: false,
         canHaveAnswer: true,
         canHavePageBreakBefore: true,
         canHaveAlternateForm: true,
         canHaveDisplayHorizontal: true,
         canHaveOptionCorrect: true,
         canHaveOptionValue: true,
         canPopulateFromApi: true,
         field_name: 'phone_input_349890B9-1FBF-466D-B246-BCD2C7AAA190',
         label: 'Phone Number',
         col: 1,
         parentId: 'AB552FAB-3E29-4158-BD5A-08FC1407C99D',
         parentIndex: 3,
      },
   ],
};
