import { IDoctorSpecialization, type IPatient } from './types';

export const patients: IPatient[] = [
   {
      first_name: 'Henryetta',
      last_name: 'Garrique',
      email: 'jcoetzee0@netscape.com',
      status: 'examination',
      gender: 'Female',
      date_of_birth: '2015-05-10T19:28:57Z',
      patient_id: '01HW2N3H2QAJPF3Q5EZD5K3MM1',
      doctor: {
         first_name: 'Joye',
         last_name: 'Coetzee',
         doctor_id: '01HW2N3H2R1Z2VRKM91CBRK6B3',
         specialization: 'Urology',
      },
      contact_info: { address: '0261 Leroy Street', mobile: '+38094596998', city: 'Azurva' },
   },
   {
      first_name: 'Masha',
      last_name: 'Eplate',
      email: 'froy1@opensource.org',
      status: 'ill',
      gender: 'Female',
      date_of_birth: '2016-05-31T06:58:04Z',
      patient_id: '01HW2N3H2XRWXAHBDDYCZ5SEJJ',
      doctor: {
         first_name: 'Faustine',
         last_name: 'Roy',
         doctor_id: '01HW2N3H2XGHK1EZX0EES8KNJS',
         specialization: 'Cardiology',
      },
      contact_info: { address: '63 Jackson Drive', mobile: '+380124456106', city: 'Al Marj' },
   },
   {
      first_name: 'Leonardo',
      last_name: 'Prisk',
      email: 'vlissimore2@github.io',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '2001-02-05T11:19:55Z',
      patient_id: '01HW2N3H31Q1KBHM8N17ZYVR4Y',
      doctor: {
         first_name: 'Vergil',
         last_name: 'Lissimore',
         doctor_id: '01HW2N3H3139P2H6CG7NQJR0NQ',
         specialization: 'Endocrinology',
      },
      contact_info: { address: '54347 Hoffman Lane', mobile: '+380168890126', city: 'Dingyan' },
   },
   {
      first_name: 'Ward',
      last_name: 'Dominiak',
      email: 'ebrisse3@privacy.gov.au',
      status: 'examination',
      gender: 'Male',
      date_of_birth: '2007-07-04T10:01:13Z',
      patient_id: '01HW2N3H35QMVQBVFN46R6Y7R7',
      doctor: {
         first_name: 'Ed',
         last_name: 'Brisse',
         doctor_id: '01HW2N3H35RPGR42QJMK245WWK',
         specialization: 'Neurology',
      },
      contact_info: { address: '9 Carpenter Crossing', mobile: '+380825214554', city: 'Gardutanjak' },
   },
   {
      first_name: 'Dianemarie',
      last_name: 'Pieterick',
      email: 'naldous4@ucla.edu',
      status: 'ill',
      gender: 'Female',
      date_of_birth: '1992-01-08T13:41:05Z',
      patient_id: '01HW2N3H39NZXD1PZSJZH6R7MZ',
      doctor: {
         first_name: 'Nerta',
         last_name: 'Aldous',
         doctor_id: '01HW2N3H39W2SJ6CNQZSSQTEKR',
         specialization: 'Urology',
      },
      contact_info: { address: '26041 Comanche Way', mobile: '+380170923689', city: 'Gąbin' },
   },
   {
      first_name: 'Wit',
      last_name: 'Janowski',
      email: 'rmanuely5@guardian.co.uk',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '1994-07-11T04:59:12Z',
      patient_id: '01HW2N3H3DXHEZG4MC0CAYGM3A',
      doctor: {
         first_name: 'Romain',
         last_name: 'Manuely',
         doctor_id: '01HW2N3H3ETMNJP3VJ13SG2RBA',
         specialization: 'Pediatrics',
      },
      contact_info: { address: '1221 7th Center', mobile: '+38019206322', city: 'Saukkola' },
   },
   {
      first_name: 'Derril',
      last_name: 'Votier',
      email: 'yobell6@google.nl',
      status: 'ill',
      gender: 'Male',
      date_of_birth: '2013-02-17T07:25:10Z',
      patient_id: '01HW2N3H3H9BZJ2ZCN7YGZQRMP',
      doctor: {
         first_name: 'Yuma',
         last_name: 'Obell',
         doctor_id: '01HW2N3H3HETECKMH6Y9W8AR3B',
         specialization: 'Urology',
      },
      contact_info: { address: '0317 Moland Lane', mobile: '+38098789061', city: 'Jinshan' },
   },
   {
      first_name: 'Madelle',
      last_name: 'McAsgill',
      email: 'kwillard7@techcrunch.com',
      status: 'wealth',
      gender: 'Female',
      date_of_birth: '1983-04-22T02:29:24Z',
      patient_id: '01HW2N3H3K8BR7SVE6BMV81WZ8',
      doctor: {
         first_name: 'Kata',
         last_name: 'Willard',
         doctor_id: '01HW2N3H3KHK0JQVW8K85MVQE6',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '58114 Northwestern Street', mobile: '+380860097446', city: 'Katima Mulilo' },
   },
   {
      first_name: 'Korella',
      last_name: 'Figgins',
      email: 'umingasson8@cnbc.com',
      status: 'examination',
      gender: 'Female',
      date_of_birth: '1989-03-09T08:44:43Z',
      patient_id: '01HW2N3H3Q7P3G7NFNC9P3Y426',
      doctor: {
         first_name: 'Ulrikaumeko',
         last_name: 'Mingasson',
         doctor_id: '01HW2N3H3RAP9HX28RBQV5JVYQ',
         specialization: 'Gastroenterology',
      },
      contact_info: { address: '2823 Kings Terrace', mobile: '+38060051059', city: 'Muro' },
   },
   {
      first_name: 'Natalee',
      last_name: 'Landre',
      email: 'candriesse9@nature.com',
      status: 'wealth',
      gender: 'Female',
      date_of_birth: '1987-01-28T20:42:22Z',
      patient_id: '01HW2N3H3THZW751TRXDZWV6D1',
      doctor: {
         first_name: 'Constantia',
         last_name: 'Andriesse',
         doctor_id: '01HW2N3H3VGPH693PA2Y5FCAM6',
         specialization: 'Cardiology',
      },
      contact_info: { address: '91 Trailsway Alley', mobile: '+38014802361', city: 'Kannus' },
   },
   {
      first_name: 'Curry',
      last_name: 'Crimin',
      email: 'cpaddella@patch.com',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '2010-07-29T02:11:46Z',
      patient_id: '01HW2N3H3YED39NJGPPEJZWHV4',
      doctor: {
         first_name: 'Creigh',
         last_name: 'Paddell',
         doctor_id: '01HW2N3H3YPA62B0GCNMBAY8F3',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '1 Everett Road', mobile: '+380142000491', city: 'Tembilahan' },
   },
   {
      first_name: 'Leupold',
      last_name: 'Ranvoise',
      email: 'kpruceb@blog.com',
      status: 'examination',
      gender: 'Male',
      date_of_birth: '2019-04-13T10:17:49Z',
      patient_id: '01HW2N3H41VJXTK85ZK090N648',
      doctor: {
         first_name: 'Kilian',
         last_name: 'Pruce',
         doctor_id: '01HW2N3H41CHSBJ6MBKY178DW4',
         specialization: 'Cardiology',
      },
      contact_info: { address: '6 Kensington Way', mobile: '+380168860956', city: 'Poggio di Chiesanuova' },
   },
   {
      first_name: 'Gretchen',
      last_name: 'Seyers',
      email: 'tforsdikec@japanpost.jp',
      status: 'examination',
      gender: 'Female',
      date_of_birth: '2012-10-21T22:23:26Z',
      patient_id: '01HW2N3H4445P71V42GXK7NPZK',
      doctor: {
         first_name: 'Tansy',
         last_name: 'Forsdike',
         doctor_id: '01HW2N3H44W5RKDZXRP0TTWXJQ',
         specialization: 'Neurology',
      },
      contact_info: { address: '502 Katie Avenue', mobile: '+380125841581', city: 'Dragomer' },
   },
   {
      first_name: 'Yurik',
      last_name: 'Engley',
      email: 'ljewettd@jiathis.com',
      status: 'ill',
      gender: 'Male',
      date_of_birth: '2001-11-07T17:37:46Z',
      patient_id: '01HW2N3H47QBM0Y6KB53C324R7',
      doctor: {
         first_name: 'Luciano',
         last_name: 'Jewett',
         doctor_id: '01HW2N3H47BFRWQSXSTWSDART5',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '19 Clemons Way', mobile: '+38015829141', city: 'Dabu' },
   },
   {
      first_name: 'Rockey',
      last_name: 'Lawleff',
      email: 'jdeeke@wordpress.com',
      status: 'examination',
      gender: 'Male',
      date_of_birth: '2014-10-29T06:13:14Z',
      patient_id: '01HW2N3H4AQKQMNGTNT5A6CXXQ',
      doctor: {
         first_name: 'Jase',
         last_name: 'Deek',
         doctor_id: '01HW2N3H4ATX3HXTBZKXTGEKQ1',
         specialization: 'Dermatology',
      },
      contact_info: { address: '1 Duke Lane', mobile: '+380185176849', city: 'Guadalupe' },
   },
];

export const specializations: IDoctorSpecialization[] = [
   'Cardiology',
   'Dermatology',
   'Neurology',
   'Pediatrics',
   'Oncology',
   'Orthopedics',
   'Psychiatry',
   'Urology',
   'Gastroenterology',
   'Endocrinology',
];
