import { type IPatient } from './types';

export const patients: IPatient[] = [
   {
      first_name: 'Silvanus',
      last_name: 'Donson',
      email: 'jtorregiani0@smugmug.com',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '3/21/1982',
      patient_id: '01HVTTK3WNCJD241HBP7P2TXB8',
      doctor: {
         first_name: 'Jerad',
         last_name: 'Torregiani',
         doctor_id: '01HVTTK3WN8Y9F1X1R93HH504E',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '0421 Calypso Lane', mobile: '+380867675964', city: 'Betafo' },
   },
   {
      first_name: 'Louie',
      last_name: 'Saffran',
      email: 'cmckelvie1@netlog.com',
      status: 'examination',
      gender: 'Male',
      date_of_birth: '7/8/1990',
      patient_id: '01HVTTK3WRHA6WJDVJYXRVPYPC',
      doctor: {
         first_name: 'Carroll',
         last_name: 'McKelvie',
         doctor_id: '01HVTTK3WRNM4DB4YJW09D78J7',
         specialization: 'Urology',
      },
      contact_info: { address: '6 Corben Point', mobile: '+380187702269', city: 'Perístasi' },
   },
   {
      first_name: 'Wilden',
      last_name: 'Villalta',
      email: 'mhemshall2@ft.com',
      status: 'examination',
      gender: 'Male',
      date_of_birth: '10/4/1999',
      patient_id: '01HVTTK3WTHFTCEXH9QZK5XRJ9',
      doctor: {
         first_name: 'Murvyn',
         last_name: 'Hemshall',
         doctor_id: '01HVTTK3WTXT24QSDFJZG3GXS6',
         specialization: 'Endocrinology',
      },
      contact_info: { address: '9931 Prairie Rose Junction', mobile: '+380135661972', city: 'Nanmu' },
   },
   {
      first_name: 'Nicolis',
      last_name: 'Rakestraw',
      email: 'cdemoge3@dell.com',
      status: 'ill',
      gender: 'Male',
      date_of_birth: '2/2/2016',
      patient_id: '01HVTTK3WWR1M39EYHX3TAJAX3',
      doctor: {
         first_name: 'Chaddie',
         last_name: 'Demoge',
         doctor_id: '01HVTTK3WXT6CJ6X70CPE2JD53',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '65 Jackson Alley', mobile: '+380880452508', city: 'Bamenda' },
   },
   {
      first_name: 'Melamie',
      last_name: 'Bispham',
      email: 'frickersy4@businesswire.com',
      status: 'examination',
      gender: 'Female',
      date_of_birth: '12/10/2000',
      patient_id: '01HVTTK3X0QXRK0BXMAGSBZAHN',
      doctor: {
         first_name: 'Fulvia',
         last_name: 'Rickersy',
         doctor_id: '01HVTTK3X0XB0WPEYP70DNJNDE',
         specialization: 'Endocrinology',
      },
      contact_info: { address: '285 Vernon Drive', mobile: '+38029449028', city: 'Fílla' },
   },
   {
      first_name: 'Jefferson',
      last_name: 'Scarth',
      email: 'randrei5@1688.com',
      status: 'ill',
      gender: 'Male',
      date_of_birth: '9/17/2009',
      patient_id: '01HVTTK3X3WBNJ56ANJDND9ZGH',
      doctor: {
         first_name: 'Richmound',
         last_name: 'Andrei',
         doctor_id: '01HVTTK3X3K4A2RSPM79P3F73J',
         specialization: 'Pediatrics',
      },
      contact_info: { address: '7 Golf Drive', mobile: '+380152370768', city: 'Huating' },
   },
   {
      first_name: 'Frants',
      last_name: 'Yeldham',
      email: 'rgrisenthwaite6@i2i.jp',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '2/3/1995',
      patient_id: '01HVTTK3X6Q6JK7HRQKJRSVT7H',
      doctor: {
         first_name: 'Rodolph',
         last_name: 'Grisenthwaite',
         doctor_id: '01HVTTK3X65PZ9VPCYW9A1J73V',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '6 Brentwood Center', mobile: '+38061741408', city: 'Karibib' },
   },
   {
      first_name: 'Butch',
      last_name: 'Stegel',
      email: 'sdobson7@webeden.co.uk',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '8/27/2016',
      patient_id: '01HVTTK3X8V8V3KV6J0FJGA1PW',
      doctor: {
         first_name: 'Scotti',
         last_name: 'Dobson',
         doctor_id: '01HVTTK3X8DMVEQ8Y3TFHM44J2',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '6 Sugar Trail', mobile: '+38014919892', city: 'Tsurib' },
   },
   {
      first_name: 'Jessika',
      last_name: 'Saunderson',
      email: 'ptwittey8@stumbleupon.com',
      status: 'examination',
      gender: 'Female',
      date_of_birth: '7/7/2007',
      patient_id: '01HVTTK3XA2F8WEG0SRAR7117M',
      doctor: {
         first_name: 'Perry',
         last_name: 'Twittey',
         doctor_id: '01HVTTK3XAQ69MX3MG94G3JRS8',
         specialization: 'Psychiatry',
      },
      contact_info: { address: '987 Hayes Parkway', mobile: '+380133473940', city: 'Pindamonhangaba' },
   },
   {
      first_name: 'Dolley',
      last_name: 'Sayward',
      email: 'hwaulker9@blogger.com',
      status: 'wealth',
      gender: 'Female',
      date_of_birth: '6/9/2010',
      patient_id: '01HVTTK3XC4C2A44HJ82B1Z9N6',
      doctor: {
         first_name: 'Hetti',
         last_name: 'Waulker',
         doctor_id: '01HVTTK3XC1SZ55X73VYRKZ59K',
         specialization: 'Cardiology',
      },
      contact_info: { address: '8153 Banding Street', mobile: '+38003273017', city: 'Nanxing' },
   },
   {
      first_name: 'Lance',
      last_name: 'Francioli',
      email: 'swraxalla@dailymotion.com',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '1/18/1987',
      patient_id: '01HVTTK3XDVVADNRGCBPSDKEGN',
      doctor: {
         first_name: 'Stern',
         last_name: 'Wraxall',
         doctor_id: '01HVTTK3XD6DCA2Y5F4WR58M69',
         specialization: 'Pediatrics',
      },
      contact_info: { address: '11 Acker Parkway', mobile: '+38096576804', city: 'Mocoa' },
   },
   {
      first_name: 'Garvin',
      last_name: 'Jaquin',
      email: 'wtolumellob@reddit.com',
      status: 'examination',
      gender: 'Male',
      date_of_birth: '1/16/2014',
      patient_id: '01HVTTK3XFXHRC1G962G1C9PGJ',
      doctor: {
         first_name: 'Waldemar',
         last_name: 'Tolumello',
         doctor_id: '01HVTTK3XF34AMNF3D0A70S6TZ',
         specialization: 'Cardiology',
      },
      contact_info: { address: '8605 Holmberg Plaza', mobile: '+380102505782', city: 'Chernoyerkovskaya' },
   },
   {
      first_name: 'Heall',
      last_name: 'Bonner',
      email: 'tmcgahyc@hugedomains.com',
      status: 'wealth',
      gender: 'Male',
      date_of_birth: '10/18/1987',
      patient_id: '01HVTTK3XGPM5QWVVR5E57D3WR',
      doctor: {
         first_name: 'Turner',
         last_name: 'McGahy',
         doctor_id: '01HVTTK3XGJCP089RA0BMJ4NEF',
         specialization: 'Oncology',
      },
      contact_info: { address: '42570 Waywood Center', mobile: '+380838056284', city: 'Shiniu' },
   },
   {
      first_name: 'Yelena',
      last_name: 'Beckerleg',
      email: 'amugridged@github.com',
      status: 'ill',
      gender: 'Female',
      date_of_birth: '1/10/2016',
      patient_id: '01HVTTK3XJEZN4CZRA6JRAGK9F',
      doctor: {
         first_name: 'Aurel',
         last_name: 'Mugridge',
         doctor_id: '01HVTTK3XJ32HHQ6EN8561G37X',
         specialization: 'Neurology',
      },
      contact_info: { address: '831 Moose Junction', mobile: '+38011417168', city: 'Huanglong' },
   },
   {
      first_name: 'Vivia',
      last_name: 'Sammon',
      email: 'pvenarde@freewebs.com',
      status: 'wealth',
      gender: 'Female',
      date_of_birth: '2/24/2001',
      patient_id: '01HVTTK3XMQ8Q051F4BTGRYJR8',
      doctor: {
         first_name: 'Pegeen',
         last_name: 'Venard',
         doctor_id: '01HVTTK3XM5ZGXQZ0XSPSZQYS3',
         specialization: 'Orthopedics',
      },
      contact_info: { address: '152 Lake View Way', mobile: '+38066744260', city: 'Vicente Guerrero' },
   },
];
